#!/usr/bin/env python3
"""
Rebuilds subjects_meta.json + subjects/<slug>.json from ALL exam JSON files
(ssc_cgl.json, ssc_chsl.json, sbi_po.json, etc). Run this any time questions
change in any exam file, so Practice by Subject stays in sync with the
per-exam mock tests. Previously these files were never regenerated by the
CSV converter, which is why newly added Sheet questions never appeared under
Practice by Subject even though they showed up correctly in mock tests.

Usage:
    python3 build_subjects.py <folder containing exam .json files>

Produces, inside that same folder:
    subjects_meta.json
    subjects/<slug>.json   (one per subject)
"""
import json, os, sys, glob

# Canonicalise subject-name variants so the same subject doesn't get split
# into multiple Practice-by-Subject entries (e.g. "General Awareness" and
# "General Knowledge" are treated as the same pool). Extend this as new
# variants show up in the Sheet.
SUBJECT_ALIASES = {
    "general knowledge": "General Awareness",
    "general awareness": "General Awareness",
    "gk": "General Awareness",
    "quantitative aptitude": "Quantitative Aptitude",
    "quant": "Quantitative Aptitude",
    "maths": "Quantitative Aptitude",
    "mathematics": "Quantitative Aptitude",
    "english comprehension": "English Comprehension",
    "english language": "English Comprehension",
    "general english": "English Comprehension",
    "general intelligence & reasoning": "General Intelligence & Reasoning",
    "reasoning": "General Intelligence & Reasoning",
    "polity": "Polity",
    "economics": "Economics",
    "geography": "Geography",
    "current affairs": "Current Affairs",
}

# Subjects that directly test English/Hindi language skill should never carry
# a translated q_hi/opts_hi into the shared subject pool either — keep the
# pool consistent with the per-exam files.
ENGLISH_SKILL_SUBJECTS = {"English Comprehension"}

def slugify(s):
    s = (s or "").lower().strip()
    out = []
    prev_us = False
    for ch in s:
        if ch.isalnum():
            out.append(ch)
            prev_us = False
        else:
            if not prev_us:
                out.append("_")
                prev_us = True
    return "".join(out).strip("_")

def canonical_subject(raw):
    key = (raw or "").strip().lower()
    return SUBJECT_ALIASES.get(key, (raw or "Uncategorized").strip())

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 build_subjects.py <folder>")
        sys.exit(1)
    folder = sys.argv[1]
    exam_files = [
        f for f in glob.glob(os.path.join(folder, "*.json"))
        if os.path.basename(f) not in ("meta.json", "subjects_meta.json")
        and not os.path.basename(f).startswith("subjects")
    ]

    pools = {}  # canonical subject name -> list of questions
    total_seen = 0
    for path in exam_files:
        try:
            data = json.load(open(path, encoding="utf-8"))
        except Exception as e:
            print(f"  skip {path}: {e}")
            continue
        tests = data.get("tests", [])
        for t in tests:
            for q in t.get("questions", []):
                total_seen += 1
                subj = canonical_subject(q.get("subject"))
                qq = dict(q)  # shallow copy
                if subj in ENGLISH_SKILL_SUBJECTS:
                    qq.pop("q_hi", None)
                    qq.pop("opts_hi", None)
                pools.setdefault(subj, []).append(qq)

    subjects_dir = os.path.join(folder, "subjects")
    os.makedirs(subjects_dir, exist_ok=True)

    meta_out = {}
    for subj, qs in pools.items():
        slug = slugify(subj)
        meta_out[slug] = {"name": subj, "count": len(qs)}
        json.dump({"questions": qs}, open(os.path.join(subjects_dir, slug + ".json"), "w", encoding="utf-8"),
                   ensure_ascii=False, indent=2)

    json.dump(meta_out, open(os.path.join(folder, "subjects_meta.json"), "w", encoding="utf-8"),
               ensure_ascii=False, indent=2)

    print(f"Scanned {len(exam_files)} exam file(s), {total_seen} questions total.")
    print(f"Built {len(meta_out)} subject pools:")
    for slug, m in sorted(meta_out.items(), key=lambda kv: -kv[1]["count"]):
        print(f"  {slug:35s} {m['name']:35s} {m['count']} questions")

if __name__ == "__main__":
    main()
